Repository Yakov-Varnaev/BBQ-manager, pull requests merged in 2022-08, with the labels that each got.

#11 empl model
  bbq_manager/settings.py
  employee/__init__.py
  employee/admin.py
  employee/apps.py
  employee/migrations/0001_empoyee_model.py
  employee/migrations/__init__.py
  employee/models.py
  employee/tests.py
  employee/views.py
Labels: enhancement

#12 master procedure model and empl fix
  bbq_manager/settings.py
  employee/migrations/0001_empoyee_model.py
  employee/models.py
  employees/__init__.py
  employees/admin.py
  employees/apps.py
  employees/migrations/0001_employees_models.py
  employees/migrations/__init__.py
  employees/models.py
  employees/tests.py
  employees/views.py
Labels: enhancement

#14 purchase model
  bbq_manager/settings.py
  purchases/__init__.py
  purchases/admin.py
  purchases/apps.py
  purchases/migrations/0001_purchace_model.py
  purchases/migrations/__init__.py
  purchases/models.py
  purchases/tests.py
  purchases/views.py
Labels: enhancement

#15 used materials model
  inventory/models.py
  purchases/models.py
Labels: enhancement

#18 crud
  bbq_manager/settings.py
  bbq_manager/urls.py
  bbq_manager/yasg.py
  procedures/serializers.py
  procedures/services.py
  procedures/tests.py
  procedures/urls.py
  procedures/views.py
  pytest.ini
Labels: enhancement

#2 #1
  .gitignore
  core/services.py
  core/tests.py
  docs/models.md
  inventory/services.py
  inventory/tests.py
  procedures/tests.py
  requirements.txt
Labels: enhancement

#24 archive view mixin
  core/mixins/__init__.py
  core/mixins/views.py
Labels: enhancement

#25 docs upd
  docs/BBQ db.png
  docs/models.md
Labels: documentation, enhancement

#29 17 crud basetests for api
  core/tests.py
  procedures/tests.py
Labels: enhancement

#46 44 write docstrings to base test classes
  core/tests.py
  procedures/services.py
Labels: documentation

#47 19 crud for employee
  bbq_manager/urls.py
  bbq_manager/yasg.py
  core/mixins/views.py
  core/services.py
  core/tests.py
  employees/migrations/0001_employees_models.py
  employees/migrations/0002_coef_to_coefficient.py
  employees/migrations/0003_master_procedure_coef_to_coefficient.py
  employees/models.py
  employees/serializers.py
  employees/services.py
  employees/tests.py
  employees/urls.py
  employees/views.py
  procedures/models.py
  procedures/services.py
  procedures/tests.py
  procedures/views.py
  purchases/migrations/0001_purchace_model.py
  purchases/migrations/0002_used_material_model.py
Labels: enhancement

#49 #6
  bbq_manager/urls.py
  core/tests.py
  employees/tests.py
  purchases/serializers.py
  purchases/services.py
  purchases/tests.py
  purchases/urls.py
  purchases/views.py
Labels: enhancement

#72 62 relocate material service to baseservice
  core/services.py
  employees/serializers.py
  employees/services.py
  employees/tests.py
  employees/urls.py
  employees/views.py
  inventory/tests.py
  purchases/migrations/0004_relation_name_purchases.py
  purchases/models.py
Labels: enhancement

#87 84 add new models
  bbq_manager/settings.py
  bbq_manager/yasg.py
  dump_db.sh
  employees/fixtures/fixtures.json
  employees/models.py
  inventory/fixtures/fixtures.json
  inventory/migrations/0003_add_objects.py
  inventory/models.py
  inventory/urls.py
  inventory/views.py
  objects/__init__.py
  objects/admin.py
  objects/apps.py
  objects/fixtures/fixtures.json
  objects/migrations/0001_add_objects.py
  objects/migrations/0002_null_parent.py
  objects/migrations/__init__.py
  objects/models.py
  objects/tests.py
  objects/views.py
  procedures/fixtures/fixtures.json
  procedures/migrations/0003_add_objects.py
  procedures/models.py
  purchases/fixtures/fixtures.json
  purchases/tests.py
  users/fixtures/fixtures.json
Labels: enhancement

#91 83 migration to new db schema
  bbq_manager/settings.py
  bbq_manager/yasg.py
  core/tests.py
  dump_db.sh
  employees/fixtures/fixtures.json
  employees/migrations/0005_employee_object.py
  employees/models.py
  employees/tests.py
  employees/urls.py
  employees/views.py
  inventory/fixtures/fixtures.json
  inventory/migrations/0003_add_objects.py
  inventory/models.py
  inventory/serializers.py
  inventory/tests.py
  inventory/urls.py
  inventory/views.py
  objects/__init__.py
  objects/admin.py
  objects/apps.py
  objects/fixtures/fixtures.json
  objects/migrations/0001_add_objects.py
  objects/migrations/0002_null_parent.py
  objects/migrations/__init__.py
  objects/models.py
  objects/tests.py
  objects/views.py
  procedures/fixtures/fixtures.json
  procedures/migrations/0003_add_objects.py
  procedures/models.py
  procedures/tests.py
  purchases/fixtures/fixtures.json
  purchases/tests.py
  purchases/urls.py
  users/fixtures/fixtures.json
Labels: enhancement

#93 #92
  core/services.py
  core/tests.py
  employees/fixtures/fixtures.json
  employees/models.py
  employees/tests.py
  employees/views.py
  inventory/tests.py
  procedures/tests.py
  procedures/views.py
Labels: enhancement

#99 #92 Create new models
  employees/admin.py
  employees/models.py
  inventory/admin.py
  inventory/models.py
  purchases/admin.py
  purchases/models.py
Labels: enhancement

#100 #95
  core/tests.py
  employees/migrations/0006_remove_employee_coefficient_alter_employee_object.py
  employees/tests.py
  inventory/admin.py
  inventory/migrations/0004_remove_material_price_stock_productmaterial.py
  inventory/migrations/0006_alter_stock_material.py
  inventory/migrations/0007_alter_productmaterial_material.py
  inventory/models.py
  inventory/serializers.py
  inventory/services.py
  inventory/tests.py
  inventory/urls.py
  inventory/views.py
  purchases/admin.py
  purchases/migrations/0005_remove_purchase_procedures_and_more.py
  purchases/migrations/0006_purchase_procedures.py
  purchases/migrations/0007_alter_usedmaterial_material_and_more.py
  purchases/models.py
  purchases/tests.py
Labels: enhancement
