Repository Yakov-Varnaev/BBQ-manager, pull requests merged in 2022-09, with the labels that each got.

#103 #95
  bbq_manager/urls.py
  employees/views.py
  inventory/serializers.py
  inventory/tests.py
  inventory/urls.py
  inventory/views.py
  objects/serializers.py
  objects/urls.py
  objects/views.py
  purchases/migrations/0008_alter_usedmaterial_table.py
  purchases/migrations/0009_alter_usedmaterial_table.py
  purchases/models.py
Labels: enhancement

#104 82 warehouse
  bbq_manager/urls.py
  core/tests.py
  employees/admin.py
  employees/migrations/0006_remove_employee_coefficient_alter_employee_object.py
  employees/models.py
  employees/tests.py
  employees/views.py
  inventory/admin.py
  inventory/migrations/0004_remove_material_price_stock_productmaterial.py
  inventory/migrations/0005_alter_productmaterial_table_alter_stock_table.py
  inventory/migrations/0006_alter_stock_material.py
  inventory/migrations/0007_alter_productmaterial_material.py
  inventory/models.py
  inventory/serializers.py
  inventory/services.py
  inventory/tests.py
  inventory/urls.py
  inventory/views.py
  objects/serializers.py
  objects/urls.py
  objects/views.py
  purchases/migrations/0005_remove_purchase_procedures_and_more.py
  purchases/migrations/0006_purchase_procedures.py
  purchases/migrations/0007_alter_usedmaterial_material_and_more.py
  purchases/migrations/0008_alter_usedmaterial_table.py
  purchases/migrations/0009_alter_usedmaterial_table.py
  purchases/models.py
  purchases/tests.py
Labels: enhancement

#102 101 base search
  core/tests.py
  employees/tests.py
Labels: enhancement, good first issue

#108 37 add search materials
  inventory/tests.py
Labels: enhancement

#109 38 add procedures search
  procedures/tests.py
Labels: enhancement

#110 39 master procedures search
  core/tests.py
  employees/tests.py
  employees/views.py
Labels: enhancement

#113 111 fix search procedure
  procedures/tests.py
  procedures/views.py
Labels: bug, enhancement

#114 112 fix incorrect materials search
  inventory/tests.py
  inventory/views.py
Labels: bug, enhancement

#119 master procedure filtration
  employees/filters.py
  employees/tests.py
  employees/views.py
Labels: enhancement

#120 34 add procedure filtration
  core/services.py
  employees/filters.py
  employees/tests.py
Labels: enhancement

#121 35 table of contents
  docs/instances_UD.md
  gh-md-toc
Labels: documentation, enhancement

#123 77 add field "paid_to_employee"
  purchases/migrations/0002_purchase_paid_to_employee.py
  purchases/models.py
Labels: enhancement

#126 122 add toc
  docs/models.md
Labels: documentation
